# Rustfmt 通用模板配置文件

# 导入粒度设置为 Crate，同一 crate 的导入合并为一个 use 语句
imports_granularity = "Crate"

# 指定许可证模板文件路径（需替换为实际路径）
# license_template_path = "LICENSE"

# 最大行宽，适用于大多数项目
max_width = 100

# 使用 4 个空格缩进，Rust 社区标准
tab_spaces = 4

# 链式调用的换行宽度，提高代码可读性
chain_width = 60

# 枚举和结构体的对齐阈值，保持紧凑但清晰
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

# 格式化文档注释中的代码块
format_code_in_doc_comments = true

# 合并重复的导入
# merge_imports = true

# 按字母顺序重新组织导入
reorder_imports = true

# 移除未使用的导入
# remove_unused_imports = true

# 对短数组强制换行（长度阈值）
array_width = 60

# 使用小型标签风格（small tabs）
use_small_heuristics = "Default"

ignore = ["src/pb"]
